// Code generated by 'yaegi extract github.com/codepuree/tilo-railway-company/pkg/traincontrol'. DO NOT EDIT.

package trclib

import (
	"github.com/codepuree/tilo-railway-company/pkg/traincontrol"
	"reflect"
)

func init() {
	Symbols["github.com/codepuree/tilo-railway-company/pkg/traincontrol"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewTrainControl": reflect.ValueOf(traincontrol.NewTrainControl),

		// type definitions
		"Block":              reflect.ValueOf((*traincontrol.Block)(nil)),
		"Sensor":             reflect.ValueOf((*traincontrol.Sensor)(nil)),
		"Signal":             reflect.ValueOf((*traincontrol.Signal)(nil)),
		"Switch":             reflect.ValueOf((*traincontrol.Switch)(nil)),
		"TrainControl":       reflect.ValueOf((*traincontrol.TrainControl)(nil)),
		"TrainControlConfig": reflect.ValueOf((*traincontrol.TrainControlConfig)(nil)),
	}
}
